### ISSUE TITLE
Cron System

### ISSUE THREAD

**Issue by secondtruth** [seabreeze-project/seabreeze#1]
Implement a Cron System to allow scheduling commands to run automatically in containers based on a defined schedule.

## Details

1. **Cron Syntax Support:** Allow users to define schedules using standard cron syntax.
2. **Configuration:** Users should be able to define cron jobs in the project manifest for seamless setup.
4. **Logging and Monitoring:** Provide logs for cron jobs to monitor their execution and troubleshoot any issues.

### Example Configuration

Definition of cron jobs in the project manifest as follows:

```yaml
tasks:
  - schedule: "0 2 * * *"
    command: "/path/to/backup/script.sh"
    service: "db-service"
  - schedule: "*/5 * * * *"
    command: "php /path/to/maintenance/script.php"
    service: "web-service"
```
