### ISSUE TITLE
Docker API Proxy

### ISSUE THREAD

**Issue by secondtruth** [seabreeze-project/seabreeze#2]
Implement a Docker API Proxy to control and restrict access to Docker endpoints.

## Details

- **Endpoint Restrictions:** Allow users to specify which Docker API endpoints are accessible.
- **Configuration:** Users should be able to define allowed endpoints in
  - the project manifest (?)
  - the global configuration (?)
  - both (?)

### Optional Features

- **Logging and Monitoring:** Provide logs to monitor access and usage of Docker API endpoints.

### Example Configuration

Example configuration block for this feature:

```yaml
proxy:
  allowed_endpoints:
    - "containers"
    - "images"
    - "volumes"
    - "networks"
    - "services"
    - "tasks"
    - "events"
    - "version"
    - "info"
    - "ping"
  socket_file: "/tmp/docker.sock"
  mode: "0644"
  owner: "user:group"
```
